default_language_version:
    python: python3.8
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: check-added-large-files
      - id: mixed-line-ending
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-json
      - id: check-builtin-literals
      - id: debug-statements
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
        args:
          - --remove
      - id: trailing-whitespace
#  - repo: https://gitlab.com/pycqa/flake8
#    rev: 3.7.9
#    hooks:
#      - id: flake8
#        args:
#          - --statistics
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.4.2
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-mock-methods
      - id: python-no-log-warn
      - id: rst-backticks
  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.1.0
    hooks:
      - id: python-safety-dependencies-check
  - repo: https://github.com/asottile/seed-isort-config
    rev: v1.9.3
    hooks:
      - id: seed-isort-config
        args:
          - --application-directories
          - example
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort
        additional_dependencies:
          - isort[pyproject]
  - repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/pydocstyle
    rev: 4.0.1
    hooks:
      - id: pydocstyle
        verbose: true
        args:
          - --convention=numpy
          - --add-ignore=D100,D104,D105
        exclude: >
          (?x)^(
              .*/migrations/.*\.py$|
              .*/admin.*\.py$|
              example/manage\.py$
          )$
